[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "lightningcss-napi"
version = "0.1.0"
description = "Node-API bindings for Lightning CSS"
license = "MPL-2.0"
repository = "https://github.com/parcel-bundler/lightningcss"
edition = "2021"

[features]
default = [
  "napi",
  "napi/napi4",
  "napi/napi5",
  "napi/compat-mode",
  "napi/serde-json",
]

napi = ["dep:napi"]
napi_tokio_rt = ["napi/tokio_rt"]
visitor = ["lightningcss/visitor"]
bundler = ["dep:crossbeam-channel", "dep:rayon"]

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
serde_bytes = "0.11.5"
cssparser = "0.33.0"
lightningcss = { path = "../", features = ["nodejs", "serde"] }
parcel_sourcemap = { version = "2.1.1", features = ["json"] }
serde-detach = "0.0.1"
smallvec = { version = "1.7.0", features = ["union"] }
napi = {version = "2", default-features = false, optional = true}
crossbeam-channel = { version = "0.5.6", optional = true }
rayon = { version = "1.5.1", optional = true }
